apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-gateway-nginx-config
data:
  nginx.conf: |
      http {
          include       mime.types;
          default_type  application/octet-stream;

          sendfile        on;
          keepalive_timeout 65;

          server {
              listen 80;
              server_name localhost;

              root /var/www/html;
              index index.php index.html;

              location / {
                  try_files $uri $uri/ /index.php?$args;
              }

              location ~ \.php$ {
                  include fastcgi_params;
                  fastcgi_pass mediawiki:9000;
                  fastcgi_index index.php;
                  fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
              }

              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                  expires max;
                  log_not_found off;
              }
          }
      }
