services:
  mediawiki:
    build: .
    restart: always
    expose:
      - "9000"
    environment:
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: database
      MEDIAWIKI_DB_NAME: isd_wiki
      MEDIAWIKI_DB_USER: wikiuser
      MEDIAWIKI_DB_PASSWORD: example
      MEDIAWIKI_DB_PORT: 3306
      MEDIAWIKI_SITE_SERVER: http://localhost:8080
      MEDIAWIKI_SITE_NAME: "ISD Wiki"
      MEDIAWIKI_ADMIN_USER: admin
      MEDIAWIKI_ADMIN_PASS: admin12345
      MEDIAWIKI_SITE_LANG: en
    volumes:
      - mediawiki-html:/var/www/html
      - images:/var/www/html/images
      - mediawiki-data:/data

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mediawiki
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - mediawiki-html:/var/www/html:ro
      - images:/var/www/html/images:ro

  database:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: isd_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  mediawiki-html:
  mediawiki-data:
  images:
  db:
