apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "isd-wiki.fullname" . }}-html
  labels:
    {{- include "isd-wiki.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi