apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "isdWiki.fullname" . }}-data
  labels:
    {{- include "isdWiki.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi