apiVersion: v1
kind: Service
metadata:
  name: {{ include "isd-wiki.fullname" . }}
  labels:
    {{- include "isd-wiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mediawiki.service.type }}
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: proxy-traffic
    - name: https-app
      protocol: TCP
      port: 443
      targetPort: proxy-traffic
    - name: health
      protocol: TCP
      port: 8080
      targetPort: health-check
    - name: proxy-direct-8081
      protocol: TCP
      port: 8081
      targetPort: proxy-traffic
  selector:
    {{- include "isd-wiki.selectorLabels" . | nindent 4 }}
