apiVersion: v1
appVersion: 3.2-p1
description: 'Highly available: HA PostgreSQL cluster.'
home: https://github.com/bcgov/sso-helm-charts/tree/main/charts/patroni
name: patroni
sources:
- https://github.com/zalando/patroni
- https://github.com/zalando/spilo
- https://github.com/bcgov/spilo-chart
version: 1.6.1
