---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "patroni.fullname" . }}
  labels: {{ include "patroni.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    role: master
    {{- include "patroni.selectorLabels" . | nindent 4 }}
  sessionAffinity: None

{{- if .Values.service.enableReadOnly }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "patroni.fullname" . }}-readonly
  labels: {{ include "patroni.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    role: replica
    {{- include "patroni.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
{{- end }}
