apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mediawiki.fullname" . }}-data
  labels:
    {{- include "mediawiki.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi