apiVersion: v2
name: isd-wiki
description: A Helm chart for deploying ISD MediaWiki with a database.
version: 0.1.0
appVersion: "1.39.3"
type: application
icon: https://upload.wikimedia.org/wikipedia/commons/d/dd/MediaWiki-2020-logo.svg

dependencies:
  - name: patroni
    version: 0.0.4
    repository: https://bcgov.github.io/nr-patroni-chart
