apiVersion: v2
name: isdwiki
description: A Helm chart for deploying ISD MediaWiki with a database.
version: 0.1.0
appVersion: "1.39.3"
type: application
icon: https://upload.wikimedia.org/wikipedia/commons/d/dd/MediaWiki-2020-logo.svg

dependencies:
  - name: mariadb
    version: "11.4.7"
    repository: oci://registry-1.docker.io/bitnamicharts 
    condition: mariadb.enabled
  - name: mediawikiServer
    version: 1.0.0
    repository: file://./charts/mediawikiServer