{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ include "patroni.fullname" . }}-to-{{ include "patroni.fullname" . }}-cluster
  labels: {{ include "patroni.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels: {{ include "patroni.selectorLabels" . | nindent 10 }}
    ports:
      - port: {{ .Values.service.port }}
        protocol: TCP
      - port: 8008
        protocol: TCP
  podSelector:
    matchLabels: {{ include "patroni.selectorLabels" . | nindent 6 }}
{{- end }}
