---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "patroni.fullname" . }}
  labels: {{ include "patroni.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "patroni.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "patroni.fullname" . }}
