{{- $replicationPassword := (randAlphaNum 32) | b64enc }}
{{- $superuserPassword := (randAlphaNum 32) | b64enc }}
{{- $appDbPassword := (randAlphaNum 32) | b64enc }}

{{- if not .Values.secretOverride }}

{{- $secretName := print (include "patroni.fullname" .) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if not $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ $secretName }}
  labels: {{ include "patroni.labels" . | nindent 4 }}
type: Opaque
data:
  replication-username: {{ default "replication" .Values.credentials.replicationUsername | b64enc }}
  replication-password: {{ $replicationPassword }}
  superuser-username: {{ default "postgres" .Values.credentials.superuserUsername | b64enc }}
  superuser-password: {{ $superuserPassword }}
  app-db-name: {{ default "app" .Values.credentials.appDbName | b64enc }}
  app-db-username: {{ default "app" .Values.credentials.appDbUserame | b64enc }}
  app-db-password: {{ $appDbPassword }}

{{- end }}
{{- end }}
